# Defines dotfiles path
export dotfiles="$HOME/.dotfiles"

# Defines profiles path
profiles="$dotfiles/profiles.d"

plugins=(git)

export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

source $dotfiles/z.sh
